version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - 2181:2181
      - 8080:8080
    volumes:
      - ./data:/data
      - ./datalog:/datalog
    networks:
      - zookeeper_net
  zoonavigator:
    image: elkozmon/zoonavigator:1.1.0
    container_name: zoonavigator
    ports:
      - 9000:9000
    environment:
      CONNECTION_LOCALZK_NAME: docker-zookeeper
      CONNECTION_LOCALZK_CONN: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - zookeeper_net

networks:
  zookeeper_net:
    name: zookeeper_net
