version: '3.5'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - es_net
  kibana:
    image: kibana:7.12.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - es_net

networks:
  es_net:
    name: es_net

    