version: '3.5'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: qgaye
      MYSQL_PASSWORD: qgaye
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    networks:
      - mysql_net

networks:
  mysql_net:
    name: mysql_net