version: '3.5'
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: kafka-zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - kafka_net
  kafka:
    image: bitnami/kafka:2
    container_name: kafka
    ports:
      - 9000:9000
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CLIENT_USERS: qgaye
      KAFKA_CLIENT_PASSWORDS: qgaye
    volumes: 
      - ./data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka_net
  kafak-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: docker-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - kafka_net 

networks:
  kafka_net:
    name: kafka_net
