version: '3.5'
services:
  redis:
    image: redis:6
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    networks:
      - redis_net

networks:
  redis_net:
    name: redis_net
